### PR TITLE
Update version so we can upload to yolapi

### PR DESCRIPTION
**Pull request by stormf**

### CODE REVIEW

**Comment by adrianmoisey** [comment]
Why not used the unforked version?

**Comment by stormf** [comment]
Setting the version to something we control to mark this point as a release, for the purposes of uploading to our internal package index.

It's not on pypi yet (which should be the authority on versions), and I don't want to ask the author to go through the effort if we end up not using this thing. If we do, and he uploads it to pypi then I'll kill this fork.

**Comment by adrianmoisey** [comment]
:+1:

**Comment by stormf** [comment]
TIL https://www.python.org/dev/peps/pep-0440/

**Pull request merged**
